const fs = require('fs');
const file = 'phone_preview.html';
let lines = fs.readFileSync(file, 'utf8').split('\n');

// Replace lines 955-971 (0-indexed: 954-970)
const newLines = [
"    permesso: [",
"        { id: 'per-rinnovo-lavoro', catId: 'rinnovo', title: 'Rinnovo per Lavoro - Guida Completa', ref: 'Art. 5 comma 4 T.U.I.', isNew: true, dateAdded: '2026-04-17', desc: 'GUIDA COMPLETA al rinnovo del permesso di soggiorno per lavoro subordinato. Include costi, documenti, tempistiche e procedura passo-passo. Fonti: Polizia di Stato, Ministero dell\\'Interno, Poste Italiane, Portale Immigrazione.', reqs: ['QUANDO: Almeno 60 gg PRIMA della scadenza. Max 60 gg DOPO.','ATTENZIONE: Dopo 60 gg senza domanda = irregolare + espulsione.','Contratto di lavoro attivo (determinato o indeterminato).','Reddito minimo: Assegno Sociale (7.002 euro/anno).','Con familiari: +50% per ogni familiare a carico.','Passaporto in corso di validita.','Assenza condanne penali gravi.'], duration: '1 o 2 anni (pari al contratto)', docs: ['Passaporto + fotocopia TUTTE le pagine.','Permesso attuale (originale + copia).','Codice Fiscale / Tessera Sanitaria.','Contratto di lavoro o UNILAV.','Ultime 3 buste paga.','CUD / Certificazione Unica.','730 o Modello Redditi.','Certificato di residenza.','Per colf/badanti: bollettini INPS.','Marca da bollo 16 euro.','Bollettino postale pagato.','4 fototessere recenti a colori.'], where: 'PASSO 1: Ritira Kit (busta gialla) GRATIS Sportello Amico Poste. PASSO 2: Compila Modulo 1 e 2 in STAMPATELLO PENNA NERA. NON firmare a casa! PASSO 3: Paga bollettini. PASSO 4: Porta tutto alle Poste, firma davanti operatore. Ricevi RICEVUTA. PASSO 5: Vai in Questura per IMPRONTE DIGITALI. Porta: ricevuta, passaporto, vecchio permesso, 4 foto, originali documenti. PASSO 6: Attendi SMS per RITIRO. Verifica su questure.poliziadistato.it/stranieri.' },",
"        { id: 'per-costi', catId: 'rinnovo', title: 'Costi Rinnovo Permesso 2026', ref: 'Poste Italiane - Min. Economia', isNew: true, dateAdded: '2026-04-17', desc: 'Dettaglio di TUTTE le spese per il rinnovo del permesso di soggiorno.', reqs: ['COSTI FISSI:','Spedizione Kit Postale: 30 euro.','Marca da bollo: 16 euro.','Stampa permesso elettronico: 30,46 euro (bollettino c/c 67422402).','CONTRIBUTO VARIABILE:','Fino a 1 anno: +40 euro.','Fino a 2 anni: +50 euro.','Lungo periodo UE: +100 euro.','TOTALE per 2 anni: circa 126,46 euro.','ESENZIONI: Minori, richiedenti asilo, protezione speciale.'], duration: 'Pagamento una tantum', docs: ['Bollettino c/c 67422402.','Marca da bollo 16 euro.','Contanti o carta per 30 euro spedizione.'], where: 'Ufficio Postale Sportello Amico. Bollettino pagabile anche su poste.it.' },",
"        { id: 'per-questura', catId: 'rinnovo', title: 'Appuntamento Questura - Cosa Portare', ref: 'poliziadistato.it', isNew: true, dateAdded: '2026-04-17', desc: 'Dopo aver spedito il kit riceverai convocazione per la Questura.', reqs: ['Presenza personale OBBLIGATORIA.','Impronte digitali TUTTE le dita.','Figli minori devono essere presenti.','Convocazione sulla ricevuta postale.','Verifica su questure.poliziadistato.it/stranieri.'], duration: 'Appuntamento: 30-60 min. Rilascio: da 60 gg a 6+ mesi.', docs: ['Ricevuta di convocazione.','Ricevuta assicurata postale ORIGINALE.','Passaporto ORIGINALE + fotocopie.','Vecchio permesso ORIGINALE.','4 fototessere a COLORI.','Ricevute bollettini.','ORIGINALI tutti i documenti del kit.'], where: 'Questura provincia (Ufficio Immigrazione). RITIRO: SMS o verifica online.' },",
"        { id: 'per-primo', catId: 'primo', title: 'Primo Rilascio per Lavoro', ref: 'Art. 22 T.U.I.', isNew: false, desc: 'Procedura per chi entra in Italia con visto lavoro subordinato.', reqs: ['Visto d\\'ingresso valido.','Nulla Osta Sportello Unico.','Contratto di soggiorno.','Codice Fiscale.'], duration: '1 o 2 anni', docs: ['Passaporto con visto.','Nulla Osta.','Contratto soggiorno.','Codice Fiscale.'], where: 'Sportello Unico Immigrazione poi Kit Postale.' },",
"        { id: 'per-conv', catId: 'conversione', title: 'Conversione da Studio a Lavoro', ref: 'Art. 6 T.U.I.', isNew: true, desc: 'Chi ha permesso studio puo convertirlo in lavoro se laureato in Italia.', reqs: ['Laurea conseguita in Italia.','Proposta di lavoro.','Reddito adeguato.'], duration: '2 anni (Rinnovabile)', docs: ['Certificato laurea.','Modello Q.','Contratto lavoro.'], where: 'Portale ALI Ministero Interno + Sportello Unico.' },",
"        { id: 'per-novita', catId: 'novita', title: 'Circolare Rinnovi Veloci 2026', ref: 'Min. Interno', isNew: true, dateAdded: '2026-04-10', desc: 'Nuove disposizioni per velocizzare i rinnovi.', reqs: ['Prenotazione online Portale Immigrazione.','Verifica stato pratica in tempo reale.','Obiettivo: rilascio entro 60 giorni.'], duration: 'In vigore dal 2026', docs: ['Credenziali Portale Immigrazione.'], where: 'portaleimmigrazione.it' }",
"    ],",
"    carta: [",
"        { id: 'car-1', catId: 'requisiti', title: 'Requisiti Reddito 2026', ref: 'INPS aggiornato', isNew: true, desc: 'Importi per permesso UE soggiornanti lungo periodo.', reqs: ['Reddito > Assegno Sociale (7.002 euro).','Certificazione Lingua A2.','5 anni residenza continua.','No condanne penali.'], duration: 'Illimitata (aggiornamento 10 anni)', docs: ['Certificazione storica residenza.','CUD ultimi 3 anni.','Idoneita alloggiativa.','Casellario giudiziale.','Certificazione A2.'], where: 'Ufficio Postale Kit Giallo poi Questura.' },",
"        { id: 'car-2', catId: 'documenti', title: 'Certificato Idoneita Alloggiativa', ref: 'D.M. 5 luglio 1975', isNew: false, desc: 'Attesta che l\\'alloggio rispetta i parametri di legge.', reqs: ['Planimetria catastale.','Contratto affitto registrato.','Certificato agibilita.'], duration: 'Validita 6-12 mesi', docs: ['Modulo richiesta Comune.','Marca bollo 16 euro.','Certificato impianti.'], where: 'Ufficio Tecnico Comune di residenza.' }",
"    ],",
"    cittadinanza: [",
"        { id: 'cit-1', catId: 'residenza', title: 'Cittadinanza per 10 anni Residenza', ref: 'Legge 91/1992 Art. 9', isNew: false, desc: 'Concessione cittadinanza per stranieri residenti da 10 anni.', reqs: ['10 anni residenza ininterrotta.','Reddito sufficiente ultimi 3 anni.','Lingua B1 certificata.','No condanne penali.'], duration: '24-36 mesi', docs: ['Certificato nascita legalizzato.','Penale estero apostillato.','Certificazione B1.','Contributo 250 euro.'], where: 'Portale Cives Ministero Interno (SPID o CIE).' },",
"        { id: 'cit-2', catId: 'matrimonio', title: 'Cittadinanza per Matrimonio', ref: 'Legge 91/1992 Art. 5', isNew: true, desc: 'Dopo 2 anni residenza post-matrimonio (1 anno con figli).', reqs: ['Matrimonio valido e trascritto.','Convivenza effettiva.','No condanne penali.','Lingua B1.'], duration: 'Circa 24 mesi', docs: ['Atto matrimonio.','Passaporto e permesso.','Contributo 250 euro.','Certificazione B1.'], where: 'Prefettura online (SPID).' },",
"        { id: 'cit-3', catId: 'iure-sanguinis', title: 'Cittadinanza Iure Sanguinis', ref: 'Circolare K28.1/1991', isNew: false, desc: 'Riconoscimento cittadinanza per discendenza da avo italiano.', reqs: ['Avo italiano senza rinuncia.','Documentazione linea genealogica.','No naturalizzazione straniera.'], duration: 'Da 6 mesi a 3+ anni', docs: ['Estratto nascita avo.','Certificato non naturalizzazione.','Certificati tutta la linea.'], where: 'Consolato o Comune di residenza.' }",
"    ],"
];

// Replace lines 954-970 (0-indexed)
lines.splice(954, 17, ...newLines);

fs.writeFileSync(file, lines.join('\n'), 'utf8');
console.log('Done! Lines 955-971 replaced successfully with clean UTF-8 data.');
